version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "emptop:1:1, updemptop:1:1, tasktop:1:1, updtasktop:1:1"
  server:
    build:
      context: ./lab3server
    ports:
      - "8010:8010"
    expose:
      - "8010"
  conserver:
    build:
      context: ./lab3conserv
    ports:
      - "8888:8888"
    expose:
      - "8888"
  crud:
#    network_mode: "overlay"
    ports:
      - "8001:8001"
    build:
      context: ./Lab_3
    depends_on:
      - server
      - conserver
      - kafka
  client:
    ports:
      - "8002:8002"
    build:
      context: ./lab3client
    depends_on:
      - server
      - conserver
      - kafka